format_version: 10
pipelines:
  roboshop-tf-apply:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-36887ae:
        git: https://github.com/Poornachandra3/roboshop-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:IsBYAm5FqkgJcOHm4xGpZA==:5hWQOBgpXckItg7rgH3cag2p/EOEghfLRxh3XPc7m5E=
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
              - exec: { command: terraform, arguments: [ "init" , "-backend-config=env-dev/state.tfvars" ] ,run_if: passed}
              - exec: { command: terraform, arguments: [ "apply" , "-auto-approve" ] ,run_if: passed}

#
#      - PROD:
#          fetch_materials: true
#          keep_artifacts: false
#          clean_workspace: false
#          environment_variables:
#            env: prod
#          approval:
#            type: success
#          jobs:
#            terraform-apply:
#              tasks:
#                - exec: { command: terraform, arguments: [ "init" , "-backend-config=env-prod/state.tfvars" ] ,run_if: passed}
#                - exec: { command: terraform, arguments: [ "apply" , "-var-file=env-prod/main.tfvars", "-auto-approve" ] ,run_if: passed}